create table advisor_orders (w_id int, d_id int, c_id int, o_id int, amount float);
insert into advisor_orders values (1, 1, 10, 101, 10.0);
insert into advisor_orders values (1, 1, 10, 102, 12.0);
insert into advisor_orders values (1, 1, 10, 103, 14.0);
insert into advisor_orders values (1, 1, 11, 104, 16.0);
insert into advisor_orders values (1, 2, 10, 105, 18.0);
insert into advisor_orders values (2, 1, 10, 201, 20.0);
select o_id, amount from advisor_orders where w_id = 1 and d_id = 1 order by o_id limit 2;
select o_id, amount from advisor_orders where w_id = 1 and d_id = 1 order by o_id limit 2;
select o_id, amount from advisor_orders where w_id = 1 and d_id = 1 order by o_id limit 2;
select o_id, amount from advisor_orders where w_id = 1 and d_id = 1 order by o_id limit 2;
select o_id, amount from advisor_orders where w_id = 1 and d_id = 1 order by o_id limit 2;
select o_id, amount from advisor_orders where w_id = 1 and d_id = 1 order by o_id limit 2;
select o_id, amount from advisor_orders where w_id = 1 and d_id = 1 order by o_id limit 2;
select o_id, amount from advisor_orders where w_id = 1 and d_id = 1 order by o_id limit 2;
show index from advisor_orders;
insert into advisor_orders values (1, 1, 12, 99, 22.0);
update advisor_orders set o_id = 98 where c_id = 12;
delete from advisor_orders where c_id = 11;
select o_id, amount from advisor_orders where w_id = 1 and d_id = 1 order by o_id limit 3;
