create table cover_idx (a int, b int, c char(4), d float);
insert into cover_idx values (1, 10, 'aa', 1.0);
insert into cover_idx values (1, 20, 'bb', 2.0);
insert into cover_idx values (1, 30, 'cc', 3.0);
insert into cover_idx values (2, 20, 'dd', 4.0);
insert into cover_idx values (3, 30, 'ee', 5.0);
create index cover_idx(a,b,c);
select a, b, c from cover_idx where a = 1 and b >= 20 and b < 40 order by b;
select a, b, c from cover_idx where a > 1 and a < 3 order by a, b;
select a, b, d from cover_idx where a = 1 and b = 20;
select count(*) as all_rows from cover_idx;
select count(*) as row_num from cover_idx where a = 1 and b >= 10 and b <= 30;
select count(c) as c_num from cover_idx where a = 2;
select count(d) as d_num from cover_idx where a = 1;
begin;
insert into cover_idx values (4, 40, 'ff', 6.0);
delete from cover_idx where a = 1 and b = 10;
abort;
select count(*) as row_num from cover_idx where a = 1;
delete from cover_idx where a = 1 and b = 10;
select count(*) as row_num from cover_idx where a = 1;
update cover_idx set b = 25 where a = 1 and b = 20;
select a, b, c from cover_idx where a = 1 and b > 10 and b < 30 order by b;
select count(*) as row_num from cover_idx where a = 1 and b >= 20 and b <= 30;
