create table cover_txn (a int, b int, c char(4), d int);
insert into cover_txn values (1, 10, 'aa', 1);
insert into cover_txn values (1, 20, 'bb', 2);
insert into cover_txn values (2, 10, 'dd', 4);
create index cover_txn(a,b,c);
begin;
insert into cover_txn values (1, 30, 'cc', 3);
select a, b, c from cover_txn where a = 1 and b >= 10 and b <= 30 order by b;
update cover_txn set b = 25 where a = 1 and b = 20;
select a, b, c from cover_txn where a = 1 and b >= 20 and b <= 30 order by b;
select count(*) as row_num from cover_txn where a = 1 and b >= 20 and b <= 30;
delete from cover_txn where a = 1 and b = 25;
select a, b, c from cover_txn where a = 1 and b >= 10 and b <= 30 order by b;
abort;
select a, b, c from cover_txn where a = 1 and b >= 10 and b <= 30 order by b;
begin;
update cover_txn set b = 22 where a = 1 and b = 20;
abort;
select count(*) as row_num from cover_txn where a = 1 and b >= 20 and b <= 30;
