create table left_partial (id int, name char(8));
create table right_partial (id int, tag char(8));
insert into left_partial values (1, 'lp1');
insert into left_partial values (2, 'lp2');
insert into left_partial values (3, 'lp3');
insert into left_partial values (4, 'lp4');
insert into right_partial values (2, 'rp2');
insert into right_partial values (4, 'rp4');
insert into right_partial values (6, 'rp6');
select left_partial.name, right_partial.tag from left_partial join right_partial on left_partial.id = right_partial.id;
explain analyze select left_partial.name, right_partial.tag from left_partial join right_partial on left_partial.id = right_partial.id;
create index right_partial(id);
select left_partial.name, right_partial.tag from left_partial join right_partial on left_partial.id = right_partial.id;
explain analyze select left_partial.name, right_partial.tag from left_partial join right_partial on left_partial.id = right_partial.id;
create table left_none (id int, name char(8));
create table right_none (id int, tag char(8));
insert into left_none values (1, 'ln1');
insert into left_none values (2, 'ln2');
insert into left_none values (3, 'ln3');
insert into right_none values (10, 'rn10');
insert into right_none values (20, 'rn20');
select left_none.name, right_none.tag from left_none join right_none on left_none.id = right_none.id;
explain analyze select left_none.name, right_none.tag from left_none join right_none on left_none.id = right_none.id;
create index right_none(id);
select left_none.name, right_none.tag from left_none join right_none on left_none.id = right_none.id;
explain analyze select left_none.name, right_none.tag from left_none join right_none on left_none.id = right_none.id;
