create table left_t (id int, code int, name char(8));
create table right_t (rid int, code int, tag char(8));
insert into left_t values (1, 10, 'l1');
insert into left_t values (2, 20, 'l2');
insert into left_t values (3, 30, 'l3');
insert into right_t values (101, 10, 'r1');
insert into right_t values (102, 40, 'r4');
select left_t.name, right_t.tag from left_t join right_t on left_t.code = right_t.code;
explain analyze select left_t.name, right_t.tag from left_t join right_t on left_t.code = right_t.code;
create index right_t(code);
select left_t.name, right_t.tag from left_t join right_t on left_t.code = right_t.code;
explain analyze select left_t.name, right_t.tag from left_t join right_t on left_t.code = right_t.code;
create table c1 (id int, v int);
create table c2 (id int, v int);
create table c3 (id int, v int);
insert into c1 values (1, 10);
insert into c2 values (1, 20);
insert into c3 values (1, 30);
insert into c1 values (2, 10);
insert into c2 values (3, 20);
insert into c3 values (3, 30);
select c1.v, c2.v, c3.v from c1 join c2 on c1.id = c2.id join c3 on c2.id = c3.id;
create table m1 (id int, code int, v int);
create table m2 (id int, code int, v int);
insert into m1 values (1, 10, 100);
insert into m1 values (1, 20, 200);
insert into m2 values (1, 10, 300);
insert into m2 values (1, 30, 400);
select m1.v, m2.v from m1 join m2 on m1.id = m2.id and m1.code = m2.code;
